services:
  db:
    image: postgres:16-bullseye
    env_file:
      - ./app/.env
    volumes:
      - hwpay-pg-vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hwpay-network
  # frontend:
  #   build: ./frontend
  #   env_file:
  #     - ./frontend/.env
  #   command: bash -c "npm run dev"
  #   # command: bash -c "npm run build && npm run start"
  #   restart: always
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - hwpay-network
  app:
    build: ./app
    env_file:
      - ./app/.env
    command: bash -c "python manage.py runserver 0.0.0.0:3001"
    # command: bash -c "uwsgi --socket 0.0.0.0:3001 --protocol http --py-autoreload 1 --ini uwsgi.ini"
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:3001"
    links:
      - db:db
      - redis:redis
    networks:
      - hwpay-network
  celery:
    build: ./app
    env_file:
      - ./app/.env
    command: bash -c "celery -A app.celery worker --loglevel=info"
    restart: always
    volumes:
      - ./app:/app
    networks:
      - hwpay-network
  celery_beat:
    build: ./app
    env_file:
      - ./app/.env
    command: bash -c "celery -A app.celery beat"
    restart: always
    volumes:
      - ./app:/app
    networks:
      - hwpay-network
  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - hwpay-network

networks:
  hwpay-network:
    driver: bridge
volumes:
  hwpay-pg-vol:
