# Generated by Django 5.1.3 on 2024-12-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='network',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='cash_register',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
