# Generated by Django 5.1.3 on 2025-01-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_alter_tip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.wallet'),
        ),
    ]
