# Generated by Django 5.1.3 on 2024-11-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('wallet', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='wallet',
        ),
        migrations.AddField(
            model_name='cashier',
            name='cash_register',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='cashier.cashregister'),
        ),
    ]
