# Generated by Django 5.1.3 on 2024-12-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_cashregister_remove_cashier_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='wallet',
        ),
    ]
