# Generated by Django 5.1.3 on 2024-12-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='cashier.payment'),
        ),
    ]
