# Generated by Django 5.1.3 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_alter_tip_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
